#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-pypi-mirror"
main = "src/index.js"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false

[dev]
ip = "127.0.0.1"
port = 8787
local_protocol = "http"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = false

[env.production]
name = "cloudflare-pypi-mirror"
#routes = [
#  { pattern = "pypi.example.com", custom_domain = true },
#  { pattern = "py-files.example.com", custom_domain = true }
#]
